<?php

return [
    'states' => [
        'us' => [
            'AL' => 'Alabama',
            'AK' => 'Alaska',
            'AZ' => 'Arizona',
            'AR' => 'Arkansas',
            'CA' => 'California',
            'CO' => 'Colorado',
            'CT' => 'Connecticut',
            'DE' => 'Delaware',
            'FL' => 'Florida',
            'GA' => 'Georgia',
            'HI' => 'Hawaii',
            'ID' => 'Idaho',
            'IL' => 'Illinois',
            'IN' => 'Indiana',
            'IA' => 'Iowa',
            'KS' => 'Kansas',
            'KY' => 'Kentucky',
            'LA' => 'Louisiana',
            'ME' => 'Maine',
            'MD' => 'Maryland',
            'MA' => 'Massachusetts',
            'MI' => 'Michigan',
            'MN' => 'Minnesota',
            'MS' => 'Mississippi',
            'MO' => 'Missouri',
            'MT' => 'Montana',
            'NE' => 'Nebraska',
            'NV' => 'Nevada',
            'NH' => 'New Hampshire',
            'NJ' => 'New Jersey',
            'NM' => 'New Mexico',
            'NY' => 'New York',
            'NC' => 'North Carolina',
            'ND' => 'North Dakota',
            'OH' => 'Ohio',
            'OK' => 'Oklahoma',
            'OR' => 'Oregon',
            'PA' => 'Pennsylvania',
            'RI' => 'Rhode Island',
            'SC' => 'South Carolina',
            'SD' => 'South Dakota',
            'TN' => 'Tennessee',
            'TX' => 'Texas',
            'UT' => 'Utah',
            'VT' => 'Vermont',
            'VA' => 'Virginia',
            'WA' => 'Washington',
            'WV' => 'West Virginia',
            'WI' => 'Wisconsin',
            'WY' => 'Wyoming',
            'DC' => 'District of Columbia',
        ],
        'ca' => [
            'AB' => 'Alberta',
            'BC' => 'British Columbia',
            'MB' => 'Manitoba',
            'NB' => 'New Brunswick',
            'NL' => 'Newfoundland and Labrador',
            'NS' => 'Nova Scotia',
            'NT' => 'Northwest Territories',
            'NU' => 'Nunavut',
            'ON' => 'Ontario',
            'PE' => 'Prince Edward Island',
            'QC' => 'Quebec',
            'SK' => 'Saskatchewan',
            'YT' => 'Yukon',
        ],
        'au' => [
            'ACT' => 'Australian Capital Territory',
            'NSW' => 'New South Wales',
            'NT' => 'Northern Territory',
            'QLD' => 'Queensland',
            'SA' => 'South Australia',
            'TAS' => 'Tasmania',
            'VIC' => 'Victoria',
            'WA' => 'Western Australia',
        ],
        'gb' => [
            'ENG' => 'England',
            'SCT' => 'Scotland',
            'WLS' => 'Wales',
            'NIR' => 'Northern Ireland',
        ],
    ],

    'shipping_zones' => [
        'domestic' => ['US'],
        'international' => ['CA', 'GB', 'AU'],
    ],

    'shipping_methods' => [
        'standard' => [
            'name' => 'Standard Shipping',
            'description' => '5-7 business days',
            'price' => 0, // Free shipping
            'delivery_days' => 7,
        ],
        'express' => [
            'name' => 'Express Shipping',
            'description' => '2-3 business days',
            'price' => 15.00,
            'delivery_days' => 3,
        ],
    ],

    'address_format' => [
        'US' => [
            'zip_label' => 'ZIP Code',
            'zip_format' => '\d{5}(-\d{4})?',
            'state_label' => 'State',
            'required_fields' => ['address', 'city', 'state', 'zip'],
        ],
        'CA' => [
            'zip_label' => 'Postal Code',
            'zip_format' => '[A-Za-z]\d[A-Za-z] \d[A-Za-z]\d',
            'state_label' => 'Province',
            'required_fields' => ['address', 'city', 'state', 'zip'],
        ],
        'GB' => [
            'zip_label' => 'Postcode',
            'zip_format' => '[A-Za-z]{1,2}\d[A-Za-z\d]? \d[A-Za-z]{2}',
            'state_label' => 'Country',
            'required_fields' => ['address', 'city', 'state', 'zip'],
        ],
        'AU' => [
            'zip_label' => 'Postcode',
            'zip_format' => '\d{4}',
            'state_label' => 'State/Territory',
            'required_fields' => ['address', 'city', 'state', 'zip'],
        ],
    ],

    'validation' => [
        'phone_formats' => [
            'US' => '^\+?1?\d{10}$',
            'CA' => '^\+?1?\d{10}$',
            'GB' => '^\+?44\d{10}$',
            'AU' => '^\+?61\d{9}$',
        ],
    ],
];
